// Structured job categories for ReelCruiter covering major industries.
export const jobCategories: string[] = [
  "Hospitality",
  "Construction",
  "IT / Technology",
  "Software Engineering",
  "Data & Analytics",
  "Design & Creative",
  "Product Management",
  "Marketing",
  "Sales",
  "Customer Service",
  "Healthcare",
  "Logistics & Supply Chain",
  "Finance & Accounting",
  "Education & Training",
  "Engineering",
  "Manufacturing",
  "Retail",
  "Administration & Office",
  "Human Resources",
  "Legal",
  "Real Estate",
  "Media & Communications",
  "Transportation & Driving",
  "Agriculture",
  "Security",
  "Cleaning & Facilities",
  "Beauty & Wellness",
  "Sports & Fitness",
  "Arts & Entertainment",
  "Government & Public Sector",
  "Non-profit & NGO",
  "Other",
];
